CREATE TABLE `SYS_AREA` (
`ID` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '区域编号',
`CODE` varchar(40) CHARACTER SET utf8 NULL DEFAULT NULL COMMENT '区域编号',
`PARENT_ID` int NOT NULL AUTO_INCREMENT COMMENT '父级',
`NAME` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '地区名称',
`DESC` varchar(256) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '描述',
`IS_DEL` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识',
`CREATE_BY` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' COMMENT '创建人',
`CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
`LAST_MODIFY_BY` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' COMMENT '最后修改人',
`LAST_MODIFY_TIME` datetime NULL,
PRIMARY KEY (`ID`) 
)
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='地区描述表';

CREATE TABLE `SYS_INSTITUION` (
`ID` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '单位ID',
`NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '单位名称',
`AREA_ID` int UNSIGNED NOT NULL COMMENT '地区ID',
`ADDRESS` text CHARACTER SET utf8 NULL COMMENT '详细地址',
`IS_DEL` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识',
`PARENT_ID` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '父组织机构单位ID',
`CREATE_BY` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' COMMENT '创建人',
`CREATE_TIME` datetime NULL COMMENT '创建时间',
`LAST_MODIFY_BY` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '最后修改人',
`LAST_MODIFY_TIME` datetime NULL COMMENT '最后修改时间',
PRIMARY KEY (`ID`) 
)
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='单位组织机构表';

CREATE TABLE `SYS_USER` (
`ID` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
`LOGIN_NAME` varchar(64) NOT NULL COMMENT '用户登录名称',
`PASSWORD` varchar(64) NOT NULL COMMENT '登录密码',
`IS_DEL` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识',
`IS_LOCK` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '账号锁标识',
`INSTITUION_ID` int NOT NULL COMMENT '账号对应的组织机构',
`POSITION_ID` int NOT NULL COMMENT '账号对应的职位信息',
`CREATE_BY` varchar(255) NULL COMMENT '创建人',
`CREATE_TIME` datetime NULL COMMENT '创建时间',
`LAST_MODIFY_BY` varchar(255) NULL COMMENT '最后更新人',
`LAST_MODIFY_TIME` datetime NULL COMMENT '最后更新时间',
`SHOW_NAME` varchar(64) NOT NULL COMMENT '账号的显示名',
PRIMARY KEY (`LOGIN_NAME`, `ID`) 
)
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='系统用户表';

CREATE TABLE `SYS_POSITION` (
`ID` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '职位ID',
`NAME` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '职位名称',
`REMARK` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT '职位描述',
`IS_DEL` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '删除标识',
`CREATE_BY` varchar(255) NULL COMMENT '创建人',
`CREATE_TIME` datetime NULL COMMENT '创建时间',
`LAST_MODIFY_BY` varchar(255) NULL COMMENT '最后修改人',
`LAST_MODIFY_TIME` datetime NULL COMMENT '最后修改时间',
PRIMARY KEY (`ID`) 
)
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='人员职位表';

CREATE TABLE `SYS_ROLE` (
`ID` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色ID',
`NAME` varchar(64) NOT NULL COMMENT '角色名称',
`IS_DEL` int UNSIGNED NULL DEFAULT 0 COMMENT '删除标识',
`IS_LOCK` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '锁标识',
`CREATE_BY` varchar(255) NULL,
`CREATE_TIME` datetime NULL,
`LAST_MODIFY_BY` varchar(255) NULL,
`LAST_MODIFY_TIME` datetime NULL,
PRIMARY KEY (`ID`) 
)
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='账号角色表';

CREATE TABLE `SYS_USER_ROLE` (
`ID` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户角色关联ID',
`USER_ID` int UNSIGNED NULL AUTO_INCREMENT COMMENT '用户ID',
`ROLE_ID` int UNSIGNED NULL COMMENT '角色ID',
`IS_DEL` int NULL,
`CREATE_BY` varchar(255) NULL,
`CREATE_TIME` datetime NULL,
`LAST_MODIFY_BY` varchar(255) NULL,
`LAST_MODIFY_TIME` datetime NULL,
PRIMARY KEY (`ID`) 
)
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='用户角色关联表';

CREATE TABLE `SYS_PERMISSION` (
`ID` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '权限ID',
`NAME` varchar NULL DEFAULT '' COMMENT '权限名称',
`TYPE` varchar NULL COMMENT '权限类型',
`URL` varchar NULL COMMENT '权限对应的URL',
`PARENT_ID` int UNSIGNED NOT NULL COMMENT '父权限ID',
`SORT` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序字段',
`CODE` varchar NULL COMMENT '权限代码字符串',
`IS_DEL` int UNSIGNED NULL,
`CREATE_BY` varchar(255) NULL,
`CREATE_TIME` datetime NULL,
`LAST_MODIFY_BY` varchar(255) NULL,
`LAST_MODIFY_TIME` datetime NULL
)
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='权限表';

CREATE TABLE `SYS_ROLE_PERMISSION` (
`ID` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色权限关联ID',
`ROLE_ID` int UNSIGNED NULL COMMENT '角色ID',
`PERMISSION_ID` int UNSIGNED NULL COMMENT '权限ID',
`IS_DEL` int UNSIGNED NULL COMMENT '删除标识',
`CREATE_BY` varchar NULL,
`CREATE_TIME` datetime NULL,
`LAST_MODIFY_BY` varchar(255) NULL,
`LAST_MODIFY_TIME` datetime NULL,
PRIMARY KEY (`ID`) 
)
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='角色权限关联表';


ALTER TABLE `SYS_INSTITUION` ADD CONSTRAINT `PK_W_AREA_ID` FOREIGN KEY (`AREA_ID`) REFERENCES `SYS_AREA` (`ID`);
ALTER TABLE `SYS_USER` ADD CONSTRAINT `PK_W_U_IN_ID` FOREIGN KEY (`INSTITUION_ID`) REFERENCES `SYS_INSTITUION` (`ID`);
ALTER TABLE `SYS_USER` ADD CONSTRAINT `PK_W_U_PO_ID` FOREIGN KEY (`POSITION_ID`) REFERENCES `SYS_POSITION` (`ID`);
ALTER TABLE `SYS_USER_ROLE` ADD CONSTRAINT `PK_W_UR_UID` FOREIGN KEY (`USER_ID`) REFERENCES `SYS_USER` (`ID`);
ALTER TABLE `SYS_USER_ROLE` ADD CONSTRAINT `PK_W_UR_RID` FOREIGN KEY (`ROLE_ID`) REFERENCES `SYS_ROLE` (`ID`);
ALTER TABLE `SYS_ROLE_PERMISSION` ADD CONSTRAINT `PK_W_RP_RID` FOREIGN KEY (`ROLE_ID`) REFERENCES `SYS_ROLE` (`ID`);
ALTER TABLE `SYS_ROLE_PERMISSION` ADD CONSTRAINT `PK_W_RP_PID` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `SYS_PERMISSION` (`ID`);

